group: bias_and_toxicity
task:
  - winobias
  - winobias_stereotypical
  - winobias_anti_stereotypical
  - toxigen_generation
  - toxigen_generation_asian
  - toxigen_generation_black
  - toxigen_generation_chinese
  - toxigen_generation_jewish
  - toxigen_generation_latino 
  - toxigen_generation_lgbtq
  - toxigen_generation_middle_east 
  - toxigen_generation_mental_dis
  - toxigen_generation_mexican
  - toxigen_generation_muslim
  - toxigen_generation_native_american
  - toxigen_generation_physical_dis
  - toxigen_generation_women
  - bold
  - bold_american_actors
  - bold_american_actresses
  - bold_asian_americans
  - bold_buddhism
  - bold_islam
  - bold_left_wing
  - bold_hispanic_and_latino_americans
  - bold_european_americans
  - bold_african_americans
  - bold_judaism
  - bold_atheism
  - bold_christianity
  - bold_sikhism
  - bold_hinduism
  - truthfulqa_mc2
  - crows_pairs
  - hendrycks_ethics
  - sycophancy
  - persona
  - advanced_ai_risk
  - bbq
  - winogender
  - winogenerated
  - ethos
  - jigsaw_toxicity
  - jigsaw_toxic_prompts
