group:
  - bias
task: bold
dataset_path: AlexaAI/bold
output_type: generate_until
training_split: train
validation_split: train
test_split: train
doc_to_text: !function utils.doc_to_text
doc_to_target: none
process_results: !function utils.process_results_gen
generation_kwargs:
  until:
    - "\n"
metric_list:
  - metric: vaderSentiment
    aggregation: mean
    higher_is_better: true
metadata:
  version: 1.0