task: jigsaw_toxicity
dataset_path: Arsive/toxicity_classification_jigsaw
output_type: generate_until
training_split: train
fewshot_split: train
test_split: test
doc_to_text: !function utils.doc_to_text
doc_to_target: none
process_results: !function utils.process_results
generation_kwargs:
  until:
    - "\n"
metric_list:
  - metric: jigsaw_toxicity
    aggregation: mean
    higher_is_better: true
metadata:
  version: 1.0
