task: winobias
dataset_path: Elfsong/Wino_Bias
output_type: loglikelihood
training_split: train
fewshot_split: train
test_split: test
doc_to_text: !function utils.doc_to_text
doc_to_target: !function utils.doc_to_target
process_results: !function utils.process_results
metric_list:
  - metric: bias_score
    aggregation: mean
    higher_is_better: true
metadata:
  version: 1.0
